
project_id = "ljcziwpohceaacdreugx"
[api]
enabled = true
port = 54321
[db]
port = 54322
[studio]
port = 54323
[inbucket]
enabled = false
port = 54324
[functions.cashfree-payment]
verify_jwt = false
[functions.cashfree-webhook]
verify_jwt = false
[functions.create-payment-table]
verify_jwt = false
